
- author: David bertram
  date:   2007-10-11 09:33:14
  comment: |
    <p>Though note that the applicants are planning to discuss/submit a revised application; however their card has been firmly marked. I wonder if this is the last we hear of the conveniently-timed announcement of the tenancy of L&#39;Amandine....</p>

- author: Ed
  date:   2007-11-07 14:06:57
  comment: |
    <p>There&#39;s a new application gone in last week:</p>  <p>07/3557/FUL Installation of new shop front.</p>  <p><a href="http://idoxwam.richmond.gov.uk:90/WAM/showCaseFile.do?&amp;appNumber=07%2F3557%2FFUL">idoxwam.richmond.gov.uk:90/WAM/showCaseFile.do?&amp;appNumber=07/3557/FUL</a></p>  <p>It&#39;s on behalf of ...</p>  <p>wait for it ...</p>  <p>ANGLO FRENCH BAKERIES LTD</p>  <p>Could it really be a new bakers? (Or is that just a "front"!?)</p>  <p>Ed</p>
