
- author: Dorothy Powell
  date:   2018-06-30 12:12:25
  comment: |
    <p>Very glad to hear this. The previous proposals did not, I thought (along with lots of other people) do justice to the potential of the site. Well done the new administration!</p>

- author: Ian
  date:   2018-06-30 14:47:39
  comment: |
    <p>I&#39;m pleasantly surprised - I never really thought the Lib Dems would stick to their pledge. I look forward to their proposals</p>

- author: David Johnston
  date:   2018-06-30 16:54:54
  comment: |
    <p>Excellent news. Need now to develop a brief and short list urban designers/architecrs to come up with ideas for the whole of the riverside area.</p>
